# Generated by Django 2.1 on 2018-08-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
