# Generated by Django 2.1 on 2018-08-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20180812_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
