# Generated by Django 2.1 on 2018-08-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_guard_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
